repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: swgsrelate
  description: A workflow for sWGS genotype likelihood calling and relatedness estimation
  author: Thomas Isensee
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
