lint: {}
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Thomas Isensee
  description: A workflow for sWGS genotype likelihood calling and relatedness estimation
  force: false
  is_nfcore: true
  name: swgsrelate
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0.0dev
